import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/component/NavBar'
import ReduxProvider from '@/redux/ReduxProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import NextAuthProvider from '@/providers/NextAuthProvider'
import SignInOut from '@/component/SignInOut'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const nextAuthSession = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NextAuthProvider session={nextAuthSession}>
            <div className='mx-10 my-[10vw]'>
              <div className='flex flex-row'>
                <NavBar/>
                <div className='w-[100px] h-[50px] bg-6FA9FF item-center absolute right-0 rounded-l-lg'>
                  <SignInOut/>
                </div>
              </div>
              {children}
            </div>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
